# Generated by Django 4.2.1 on 2023-05-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='full name', max_length=100),
            preserve_default=False,
        ),
    ]
