FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /carbonzero-data-management-be

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./entrypoint.sh .

COPY . .
ENTRYPOINT ["sh", "/carbonzero-data-management-be/entrypoint.sh"]