services:
  postgres_db:
    container_name: db
    image: postgres:15.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports: 
      - 5432:5432
  backend:
    container_name: be
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - .:/be-django
    restart: always
    image: be-django
    depends_on:
      postgres_db:
        condition: service_healthy
volumes:
  pgdata: