FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /carbonzero-data-management-dir

COPY ./carbonzero_data_management/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./carbonzero_data_management/. .

ENTRYPOINT ["sh", "/carbonzero-data-management-dir/entrypoint.sh"]