FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /carbonzero-data-management-be

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD python3 manage.py makemigrations && \
    python3 manage.py migrate && \
    python3 manage.py runserver 0.0.0.0:8000